  version: '3.1'

  services:

    ubuntu:
      image: ubuntu:18.04
      ports:
        - "80:80"
        - "443:443"
        - "25:25"
        - "465:465"
        - "587:587"
        - "9071:9071"
        - "7071:7071"
        - "389:389"
        - "636:636"
        - "993:993"
      volumes:
        - /deployments/zimbra/opt:/opt/zimbra
        - /deployments/zimbra/worker:/root/worker


          #- /var/run/docker.sock:/tmp/docker.sock:ro
