nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ~/_testing/nginx_at_80/certs_www3:/etc/nginx/certs:ro
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
    labels: 
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy 

letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
        - ~/_testing/nginx_at_80/certs_www3:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from: 
        - nginx-proxy:rw

www:
    image: nginx
    restart: always
    expose:
        - "80"
    
    volumes:
        - ~/_testing/nginx_at_80/www:/usr/share/nginx/html:ro
    environment: 
        - VIRTUAL_HOST=wpatino.local,www.wpatino.local

www2:
            image: nginx
            restart: always
            expose:
                - "80"
            
            volumes:
                - ~/_testing/nginx_at_80/www2:/usr/share/nginx/html:ro
            environment: 
                - VIRTUAL_HOST=testing.local,www.testing.local
                - LETSENCRYPT_HOST=testing.local,www.testing.local
                        

www3:
                    image: nginx
                    restart: always
                    expose:
                        - "80"
                    
                    volumes:
                        - ~/_testing/nginx_at_80/www3:/usr/share/nginx/html:ro
                    environment: 
                        - VIRTUAL_HOST=patinoimages.com,www.patinoimages.com
                        - LETSENCRYPT_HOST=patinoimages.com,www.patinoimages.com
        

        # ports:
        # - "80:80"