version: '3.1'

services:

  dbase:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: =mariadb
    ports:
      - 3306:3306
    volumes:
      - /home/wp/docker/data/mariadb:/var/lib/mysql/

